### PR TITLE
Pipeline updates for changes in build processes.

### PR DESCRIPTION
**Pull request by JohnathonMohr**
## Description

Update build pipelines to account for changes in build processes.
- New NuGet package for template processing
- Transition away from `development` branch
- Enforce dotnet 6 in AzDO pipeline

---

This checklist is used to make sure that common guidelines for a pull request are followed.
- [x] **I have read the [contribution guidelines](../CONTRIBUTING.md).**
- [x] The pull request does not introduce breaking changes.

### [General Guidelines](../CONTRIBUTING.md)
- [x] Title of the pull request is clear and informative.
- [x] Description of the pull request is clear and informative.
- [x] I have added myself to the 'assignees'.
- [x] I have added 'linked issues' if relevant.

### [Testing Guidelines](../CONTRIBUTING.md#tests)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by JohnathonMohr** [comment]
I'm not sure what's causing the Utilities tests to fail in the AzDO pipeline.  @nonik0 do you have time to investigate this?

**Comment by nonik0** [comment]
> I'm not sure what's causing the Utilities tests to fail in the AzDO pipeline. @nonik0 do you have time to investigate this? My initial hunch was a dotnet version thing, but that didn't make a difference.

The Utilities test project was updated to copy the test templates from the CLI tests. This works fine in the GH pipeline but is failing with the AzDO pipeline:
https://github.com/Azure/template-analyzer/blob/aed9d95cbf65836d0bad6030041499a7f75424ab/src/Analyzer.Utilities/Analyzer.Utilities.csproj#L14

**Comment by JohnathonMohr** [comment]
> > I'm not sure what's causing the Utilities tests to fail in the AzDO pipeline. @nonik0 do you have time to investigate this? My initial hunch was a dotnet version thing, but that didn't make a difference.
> 
> 
> 
> The Utilities test project was updated to copy the test templates from the CLI tests. This works fine in the GH pipeline but is failing with the AzDO pipeline:
> 
> https://github.com/Azure/template-analyzer/blob/aed9d95cbf65836d0bad6030041499a7f75424ab/src/Analyzer.Utilities/Analyzer.Utilities.csproj#L24-27

Right, I just don't understand *why* it's failing in AzDO...

**Comment by nonik0** [comment]
> > > I'm not sure what's causing the Utilities tests to fail in the AzDO pipeline. @nonik0 do you have time to investigate this? My initial hunch was a dotnet version thing, but that didn't make a difference.
> > 
> > 
> > The Utilities test project was updated to copy the test templates from the CLI tests. This works fine in the GH pipeline but is failing with the AzDO pipeline:
> > https://github.com/Azure/template-analyzer/blob/aed9d95cbf65836d0bad6030041499a7f75424ab/src/Analyzer.Utilities/Analyzer.Utilities.csproj#L24-27
> 
> Right, I just don't understand _why_ it's failing in AzDO...

Yup still working on that... 😅

**Review by nonik0 — APPROVED** [review]

**Review by VeraBE — APPROVED** [review]

**Pull request merged**
