### PR TITLE
Generalize XML comment enforcement

### PR DESCRIPTION
**Pull request by JohnathonMohr**
- Putting property group that generates code documentation (and enforces XML comments) into common *Directory.Build.targets* file
  - Only applies to projects that aren't tests
- Removing from all projects that declared them manually

### CODE REVIEW

**Review by yane3628 — APPROVED** [review]

**Review by VeraBE — COMMENTED** [review]
We don't need to import the new targets file, or something related, to the project files?

**Comment by JohnathonMohr** [comment]
@VeraBE Directory.Build.props and .targets are special cases that are imported automatically.  https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#directorybuildprops-and-directorybuildtargets

**Comment by VeraBE** [comment]
> @VeraBE Directory.Build.props and .targets are special cases that are imported automatically. https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#directorybuildprops-and-directorybuildtargets

Yes. but I read in a few places that we need to import Microsoft.Common.targets somehow for that to work, right? (GitHub is not letting me reply in the same conversation :O)

**Comment by JohnathonMohr** [comment]
@VeraBE that was true prior to MSBuild version 15 (noted in the link).  (Comments at the PR level [not on a line in a file] are all grouped in a single thread in GH. ☹)

**Comment by VeraBE** [comment]
@JohnathonMohr The first line of the documentation says "MSBuild projects that use the standard build process (importing Microsoft.Common.props and Microsoft.Common.targets) have several extensibility hooks that you can use to customize your build process.". Do you interpret that as the standard build process makes those imports? I checked the repo and couldn't find imports like that

**Comment by JohnathonMohr** [comment]
> @JohnathonMohr The first line of the documentation says "MSBuild projects that use the standard build process (importing Microsoft.Common.props and Microsoft.Common.targets) have several extensibility hooks that you can use to customize your build process.". Do you interpret that as the standard build process makes those imports? I checked the repo and couldn't find imports like that

@VeraBE I was just noticing that too.  I'm guessing building with `dotnet` (.NET Core and .NET 5+) do that as part of the default build process now without needing to explicitly include it in the project files (kind of like how all .cs files at the same or sub-directory are automatically included and compiled in a project file).  Still looking to verify this - but in the meantime, this does work one way or another, just not certain on the technical *how* yet.

**Review by VeraBE — APPROVED** [review]

**Comment by JohnathonMohr** [comment]
@VeraBE I think this is where the magic comes from: https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview

**Pull request merged**
